# Generated by Django 5.1.3 on 2024-11-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.CharField(max_length=10, unique=True)),
                ('party_title', models.CharField(max_length=100)),
                ('leader_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=10, unique=True)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('is_voted', models.BooleanField()),
            ],
        ),
    ]
