# Generated by Django 5.1.3 on 2024-11-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ballot_total_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='party_id',
        ),
    ]
